### PR TITLE
Add Island theme

### PR DESCRIPTION
**Pull request by leostudiooo**
I made this theme *Island* myself using *Maxon Cinema 4D 22*.

Not sure if [the link](https://rmqdg-my.sharepoint.com/personal/z265_bkj_me/_layouts/15/download.aspx?UniqueId=59a96e9f-f994-4a6b-b4b8-1e121b8daa5c) is permanent or not because I am using OneDrive for Business and it doesn't have the option of *embed*. I just downloaded the file and got the link from my download manager.

By the way, this theme is about **600 MiB large** since there are 120 pictures inside, and each of them is of 5K-resolution.

### CODE REVIEW

**Comment by prakharb5** [comment]
Just a tip, you can upload your file to a new GitHub repo and use that :)

**Comment by leostudiooo** [comment]
Yeah, I thought of that. But due to some known reasons, it's really hard to upload such a large file to GitHub (it's almost 600MiB! ), especially in China during this special time.

Thanks for your advice though.


-------- Original message --------

**Comment by t1m0thyj** [comment]
Hello, thank you for your contribution! I'm in the process of switching to a new method for adding themes to the site. Could you please resubmit your theme here: https://forms.gle/kkp9Z6CUeHCzXP277

**Comment by leostudiooo** [comment]
Much appreciation for accepting my theme!

But a problem is that, like many users and theme contributors of WinDD, I live in China, where we do *not* have easy access to Google services such as search and docs. So I wonder if there is an alternative method (i.e. Microsoft's office online) to contribute to the project or make it easier. (I can try to use google docs to fill the charts though.) By the way I suggest that you can use some CDNs (i.e. jsDelivr) to speed up the connection between users and themes.

WinDD is really a nice app and I really love using it. I've recommended it to my friends and they soon fell in love with it.

在 2021-5-28，11:16，"Timothy Johnson" ***@***.******@***.***>> 写道：


Hello, thank you for your contribution! I'm in the process of switching to a new method for adding themes to the site. Could you please resubmit your theme here: https://forms.gle/kkp9Z6CUeHCzXP277

**Pull request closed without merging**
