### PR TITLE
Add Castle Theme

### PR DESCRIPTION
**Pull request by akhilesh-balaji**
This theme uses this image taken from Microsoft: https://wallpaperhub.app/wallpapers/7661 that have been digitally modified to make it dynamic. Please note that these are not real images; only the one I have linked above is real, and the credit for that goes to Microsoft. I simply edited it to make it dynamic.

### CODE REVIEW

**Comment by akhilesh-balaji** [comment]
@t1m0thyj It says that all checks have failed. I had a look at it, and it was because it wasn't able to download the file from the link. I tested the link myself and it worked. Please have a look.

**Comment by t1m0thyj** [comment]
@akhilesh-balaji Thanks for submitting a theme 🙂  Your Google Drive link should work, I'm looking into why it didn't.

**Comment by t1m0thyj** [comment]
Please try pulling latest changes from master branch (https://github.com/t1m0thyj/WDD-themes/commit/eb00914f37d33e00bd9a8663ea3ee236b454c57a) into your fork and then see if `/check-theme` will work.

Sorry for the issues, you are the first one to submit a theme so the system is still being tested. 😛

**Comment by akhilesh-balaji** [comment]
Sure, trying that right now.

**Comment by akhilesh-balaji** [comment]
Nope, still doesn't work, @t1m0thyj 
This time, however, the error is different. It says "Unable to extract images from Castle.ddw"
This is what it says exactly:
`[Castle] Failed to extract theme from temp/Castle.ddw`

**Comment by t1m0thyj** [comment]
@akhilesh-balaji I've pushed another commit (https://github.com/t1m0thyj/WDD-themes/commit/f51f56b7ac0a0473301209b9489b0d9c8733a82d) that hopefully fixes all the errors. When I ran Check Theme locally to scan your DDW file it passes for me now.

**Comment by akhilesh-balaji** [comment]
@t1m0thyj There are a few conflicts. Trying to sort them out now.

**Comment by t1m0thyj** [comment]
Feel free to close this PR and open a new one with only the YAML file changed, if that's easier for you to do.

**Comment by akhilesh-balaji** [comment]
Yes, I think I'll do that. Conflicts, at a point, become too annoying and confusing to manage. Closing the PR now, I'll open another one in a few minutes.

**Pull request closed without merging**
