### PR TITLE
Add Abstract Cloth theme

### PR DESCRIPTION
**Pull request by HaroleDev**
One thing to note here: I forgot to name the title of the PR so this is the re-request to make sure that I followed the rules.

### CODE REVIEW

**Comment by HaroleDev** [comment]
Yeah, I messed up quite a bit...

**Comment by HaroleDev** [comment]
No that totally screwed up the wallpaper

**Comment by HaroleDev** [comment]
> No that totally screwed up the wallpaper

I fixed it after that by just compressing it from exporting in photoshop :/

**Comment by t1m0thyj** [comment]
Thanks for contributing! Your theme was added in https://github.com/t1m0thyj/WDD-themes/pull/33

**Pull request closed without merging**
