### PR TITLE
Add Castle Theme

### PR DESCRIPTION
**Pull request by akhilesh-balaji**
This theme uses this image taken from Microsoft: https://wallpaperhub.app/wallpapers/7661 that have been digitally modified to make it dynamic. Please note that these are not real images; only the one I have linked above is real, and the credit for that goes to Microsoft. I simply edited it to make it dynamic.

### CODE REVIEW

**Comment by akhilesh-balaji** [comment]
@t1m0thyj It has finally passed! Phew!

**Comment by t1m0thyj** [comment]
@akhilesh-balaji Could you update the imageCredits field to include the original source? This would be fine:
`"imageCredits": "Allard Schager/Akhilesh Balaji"`

Sorry to ask for another change, but this one shouldn't involve editing the PR if the URL stays the same 🙂

**Comment by akhilesh-balaji** [comment]
@t1m0thyj Sure, doing that now.

**Comment by akhilesh-balaji** [comment]
I just did that. Could you check whether the changes have been applied?

**Comment by t1m0thyj** [comment]
LGTM, merging and it should appear on the themes site in a minute or so

**Comment by akhilesh-balaji** [comment]
Sure, thanks for your support!

**Comment by t1m0thyj** [comment]
I've noticed that the tile for Castle theme is misaligned. This is not your fault. It's an issue with the site that I'll look into tomorrow.

**Pull request merged**
